name: research_app
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publication to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  firebase_messaging: ^15.0.3
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3
  firebase_remote_config: ^5.0.3
  firebase_performance: ^0.10.0+3
  google_ml_kit: ^0.18.0
  google_sign_in: ^6.2.1
  signature: ^5.5.0
  intl: ^0.19.0
  vibration: ^1.9.0
  audioplayers: ^6.0.0
  fl_chart: ^0.68.0
  arcore_flutter_plugin: ^0.1.0
  animated_background: ^2.0.0
  video_player: ^2.8.7
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.6
  flutter_tts: ^4.0.2
  http: ^1.2.1
  sensors_plus: ^5.0.1
  camera: ^0.11.0+1
  permission_handler: ^11.3.1
  noise_meter: ^5.0.2
  animations: ^2.0.11
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/videos/ocean.mp4
    - assets/videos/forest.mp4
    - assets/videos/sky.mp4
    - assets/app_vid.mp4
    - assets/audio/rain.mp3
    - assets/audio/forest birds.mp3
    - assets/audio/wind chimes.mp3
    - assets/audio/174 Hz - Pain Relief and Anesthesia.mp3
    - assets/audio/285 Hz - Healing and Tissue Regeneration.mp3
    - assets/audio/417 Hz - Undoing Situations and Facilitating Change.mp3
    - assets/audio/528 Hz - Transformation and Miracles (DNA Repair).mp3
    - assets/audio/639 Hz - Connecting(or)Relationships.mp3
    - assets/audio/741 Hz - Awakening Intuition and Consciousness Expansion.mp3
    - assets/audio/852 Hz - Returning to Spiritual Order.mp3
    - assets/audio/963 Hz - Awaken Perfect State and Divine Consciousness.mp3
    - assets/images/
